<template>
  <div class="detail" v-if="node">
    <h3>
    {{node.path}}
    <span v-for="label in labels" :class="label.class">{{label.text}}</span>
    </h3>
    <p class="description">
      {{node.comment.parsed.description}}
    </p>
  </div>
  <div v-else class="empty">
    <div class="tips">
      Document generated by light
    </div>
  </div>
</template>
<script>

export default {
  props: {
    node: Object
  },
  computed: {
    labels() {
      let node = this.node
      let labels = []
      if(node.isNamespace) {
        labels.push({
          class: 'label namespace',
          text: 'NS'
        })
      }
      if(node.isModule) {
        labels.push({
          class: 'label module',
          text: 'module'
        })
      }
      if(node.isConst) {
        labels.push({
          class: 'label const',
          text: 'const'
        })
      }
      if(node.isStatic) {
        labels.push({
          class: 'label property',
          text: 'static'
        })
      }
      if(node.isReadonly) {
        labels.push({
          class: 'label readonly',
          text: 'readonly'
        })
      }
      if(node.isProperty) {
        labels.push({
          class: 'label property',
          text: 'property'
        })
      }
      if(node.isMethod) {
        return {
          class: 'label method',
          text: 'method'
        }
      }
      if(node.isClass) {
        labels.push({
          class: 'label class',
          text: 'class'
        })
      }
      return labels
    }
  }
}
</script>
<style scoped lang="less">
.detail {
  width: 100%;
  height: 100%;
  padding: 0 20px;
  .description {
    font-size: 14px;
  }
  .label {
    font-size: 11px;
    color: white;
    border-radius: 3px;
    padding: 2px 4px 2px 4px; 
    display: inline-block;
    text-align: center;
    vertical-align: text-bottom;
  }
}
.empty {
  text-align: bottom;
}
.tips {
  font-size: 20px;
  color: #cccccc;
  margin-top: 40%;
}
</style>