<template>
  <div class="detail" v-if="node">
    <div class="row">
      <div class="col s12 m9 l10">
        <section>

          <h4 class="detail-title">
            {{node.path}}
            <span v-for="label in labels" class="badge" :class="label.class">{{label.text}}</span>
          </h4>

          <div class="description flow-text" v-html="node.comment.parsed.description"></div>

          <div v-if="constants.length > 0" class="split-padding"></div>
          <properties v-if="constants.length > 0" title="Constants" :properties="constants"></properties>

          <div v-if="staticProperties.length > 0" class="split-padding"></div>
          <properties v-if="staticProperties.length > 0" title="Static Properties" :properties="staticProperties"></properties>

          <div v-if="staticMethods.length > 0" class="split-padding"></div>
          <methods v-if="staticMethods.length > 0" title="Static Methods" :methods="staticMethods"></methods>

          <div v-if="properties.length > 0" class="split-padding"></div>
          <properties v-if="properties.length > 0" title="Properties" :properties="properties"></properties>

          <div v-if="methods.length > 0" class="split-padding"></div>
          <methods v-if="methods.length > 0" title="Methods" :methods="methods"></methods>

          <div class="split-padding"></div>

        </section>
      </div>
      <div class="col hide-on-small-only m3 l2"></div>
    </div>
  </div>
  <div v-else class="empty">
    <div class="tips">
      Document generated by light
    </div>
  </div>
</template>
<script>
import sortChildren from './sortChildren'
import Properties from './Properties.vue'
import Methods from './Methods.vue'

export default {
  components: {
    Properties,
    Methods
  },
  props: {
    node: Object
  },
  computed: {
    constants() {
      return sortChildren(this.node.children.filter((child) => child.isConst))
    },
    staticProperties() {
      return sortChildren(this.node.children.filter((child) => child.isStatic && child.isProperty && !child.isConst))
    },
    staticMethods() {
      return sortChildren(this.node.children.filter((child) => child.isStatic && child.isMethod))
    },
    properties() {
      return sortChildren(this.node.children.filter((child) => !child.isStatic && child.isProperty && !child.isConst))
    },
    methods() {
      return sortChildren(this.node.children.filter((child) => !child.isStatic && child.isMethod))
    },
    labels() {
      let node = this.node
      let labels = []
      if(node.isNamespace) {
        labels.push({
          class: 'label namespace',
          text: 'NS'
        })
      }
      if(node.isModule) {
        labels.push({
          class: 'label module',
          text: 'module'
        })
      }
      if(node.isConst) {
        labels.push({
          class: 'label const',
          text: 'const'
        })
      }
      if(node.isStatic) {
        labels.push({
          class: 'label property',
          text: 'static'
        })
      }
      if(node.isReadonly) {
        labels.push({
          class: 'label readonly',
          text: 'readonly'
        })
      }
      if(node.isProperty) {
        labels.push({
          class: 'label property',
          text: 'property'
        })
      }
      if(node.isMethod) {
        return {
          class: 'label method',
          text: 'method'
        }
      }
      if(node.isClass) {
        labels.push({
          class: 'label class',
          text: 'class'
        })
      }
      return labels
    }
  }
}
</script>
<style scoped lang="less">
.detail {
  width: 100%;
  height: 100%;
  padding: 0 10px;
  overflow: auto;

  .detail-title {
    font-size: 22px;
    font-weight: bold;

    .label {
      font-size: 11px;
      color: white;
      border-radius: 3px;
      float: none;
      margin-left: 4px;
      vertical-align: bottom;
      padding: 2px 5px 3px 5px;
    }

  }

  h5 {
    border-bottom: 1px solid #aaaaaa;
  }

  .description {
    font-size: 14px;
    color: #555;
  }

  .split-padding {
    padding: 15px;
  }
}
.empty {
  text-align: center;
}
.tips {
  font-size: 20px;
  color: #cccccc;
  margin-top: 40%;
}
</style>